### ISSUE TITLE
TApp的策略问题

### ISSUE THREAD

**Issue by pzjboy0924** [tearust/Chinese-wiki#11]
已经正在运营中的TApp，可以修改相关策略不，比如计费模式、Theta 值等等？

**Comment by kevingzhang** [comment]
现在还没有做到. 这个比较复杂的是如何处理目前正在挖矿的节点. 
他们加入挖矿是基于此前的一个商业模型. 如果tapp owner 单方面修改了, 应该算是违法协议. 那么这些tapp owner是否需要得到赔偿.

**Comment by kevingzhang** [comment]
如果你同意, 是否可以关闭这个 issue?
