### ISSUE TITLE
账户余额对外抵押问题

### ISSUE THREAD

**Issue by Maotweety** [tearust/Chinese-wiki#12]
账户余额对外抵押额不足导致整个账户不能操作。例如，在第一层抵押成为验证人后，
由于账户余额没有进行专户抵押资金管理，只要账户余额不足以弥补抵押额度，整个
账户将不能进行操作，只能从外面转入Tea进行补足抵押额度后才可以进行二层的一
切操作。

**Comment by liyangwood** [comment]
Fixed for wallet version 0.7.18

**Comment by liyangwood** [comment]
@kevingzhang 
![Screen Shot 2021-12-16 at 9 47 34 AM](https://user-images.githubusercontent.com/3214173/146293019-f2369806-47db-49bf-87ba-795cef8af748.png)

Please confirm the wording.

**Comment by kevingzhang** [comment]
![image](https://user-images.githubusercontent.com/1761809/146308971-56eaa5b0-8c81-49c0-9e6e-fc7a5ce36cb3.png)
this is the new UI.
the transferrable balance will be the balance deduct the miscfrozen

**Comment by kevingzhang** [comment]
@Maotweety 这个问题应该已经解决了

**Comment by Maotweety** [comment]
高效！
